/*

 STAR-BACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\Users\kphillips\git-projects\gameboy-box\space-game\assets\start-sprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 38
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define starBackgroundWidth 20
#define starBackgroundHeight 18
#define starBackgroundBank 0

extern unsigned char starBackground[];

/* End of STAR-BACKGROUND.H */
