/*

 BACKGROUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : Z:\Users\kphillips\git-projects\gb-tutorials\4_BACKGROUND\background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 37
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundWidth 40
#define backgroundHeight 18
#define backgroundBank 0

unsigned char windowMap[] =
{
  0x1e,0x0e,0x1a,0x1d,0x10,0x00,0x02,0x02,0x02,0x00
};

/* End of BACKGROUND.C */
